<?php
require('connect.php');
//echo "connected";
// prepare and bind
$stmt = $conn->prepare("INSERT INTO patient (p_name, p_dob, p_gender,p_build,p_area,p_state,p_pincode,p_email,p_phone,p_pw,p_image) VALUES (?, ?, ?,?,?,?,?,?,?,?,?)");
if($stmt){
$stmt->bind_param("sssssssssss",$name,$dob,$gender,$build,$district,$state,$pincode,$email,$phone,$pass,$img);
define ('SITE_ROOT','C:\xampp\htdocs\WEB');

// set parameters and execute
$name=$_POST['fullname'];
$dob=$_POST['dob'];
$gender=$_POST['gender'];
$build=$_POST['houseno'];
$district=$_POST['district'];
$state=$_POST['state'];
$pincode=$_POST['pincode'];
$email=$_POST['email'];
$phone=$_POST['phone'];
$pass=password_hash($_POST['password'],PASSWORD_DEFAULT);
$img=$_FILES['photo']['name'];

if ($_FILES['photo']['name']!="") {
  	// Get image name
  	$img = $_FILES['photo']['name'];
  	// Get text
  //	$image_text = mysqli_real_escape_string($db, $_POST['image_text']);

  	// image file directory
  	$target = "\images/".$img;

  //	$sql = "INSERT INTO image (image, image_text) VALUES ('$image', '$image_text')";
  	// execute query
  	//mysqli_query($db, $sql);

  	if (move_uploaded_file($_FILES['photo']['tmp_name'], SITE_ROOT.$target)) {
  	//	echo "Image uploaded successfully";
  	}else{
  		echo "Failed to upload image";
  	}
	}
	else {
	 $img="empty";
	}
//	$img="empty";
//$photo=$_POST['photo'];

if($stmt->execute())
{
	echo "inserted";
  $id=$stmt->insert_id;
  $sql="insert into patient_account(p_id,p_amount) values(?,?)";
  $stmt1=$conn->prepare($sql);
  if($stmt1)
  {
    $stmt1->bind_param("ii",$id,$amount);
    $amount=0;
    if($stmt1->execute())
    {
        //echo "done";
    }
    else {
      //echo "fail";
    }
  }
  echo "<script> window.alert('$name - Autogenerated User Id is:.$id. Please Use this to login');
  window.location.replace('../customer-login.html');

</script>";




}

else
{
	echo $stmt->error;
}
//$stmt->close();

//echo "inseted";
}


$conn->close();
?>
