<?php
require('connect.php');
//echo "connected";
session_start();
//echo $_SESSION['name'];
// prepare and bind
$stmt = $conn->prepare("INSERT INTO doctor (h_id,d_name,d_pw, d_gender,d_special,d_qual,d_email,d_phone,d_cost,d_image) VALUES (?, ?, ?,?,?,?,?,?,?,?)");
if($stmt){
$stmt->bind_param("ssssssssis",$_SESSION['id'],$name,$pass,$gender,$special,$qual,$email,$phone,$cost,$img);
define ('SITE_ROOT','C:\xampp\htdocs\WEB');
//echo "ok".$_SESSION['id'];
// set parameters and execute
$special=$_POST['specialization'];
if($_POST['specialization']=='Other')
{
  $special=$_POST['specialization2'];
}
$name=$_POST['name'];
$pass=password_hash($_POST['password'],PASSWORD_DEFAULT);
$gender=$_POST['gender'];
$qual=$_POST['qualification'];
$special=$_POST['specialization'];
$email=$_POST['email'];
$phone=$_POST['phonenumber'];
$cost=$_POST['appcost'];
$img=$_FILES['photo']['name'];

if ($_FILES['photo']['name']!="") {
  	// Get image name
  	$img = $_FILES['photo']['name'];
  	// Get text
  //	$image_text = mysqli_real_escape_string($db, $_POST['image_text']);

  	// image file directory
  	$target = "\images/".$img;

  //	$sql = "INSERT INTO image (image, image_text) VALUES ('$image', '$image_text')";
  	// execute query
  	//mysqli_query($db, $sql);

  	if (move_uploaded_file($_FILES['photo']['tmp_name'], SITE_ROOT.$target)) {
  		//echo "Image uploaded successfully";
  	}else{
  		echo "Failed to upload image";
  	}
	}
	else {
	 $img="empty";
	}
//	$img="empty";
//$photo=$_POST['photo'];

if($stmt->execute())
{
	//echo "inserted";

              echo "<script> window.alert('$name - Autogenerated User Id is:.$stmt->insert_id. Please Use this to login');
              window.location.replace('../hospital-welcome.php');

</script>";

}
//}


else
{
	echo $stmt->error;
}
//$stmt->close();

//echo "inseted";
}


$conn->close();
?>
