<?php
require('connect.php');
//echo "connected";
// prepare and bind
$stmt = $conn->prepare("INSERT INTO hospital (h_name,h_building_no,h_district,h_state,h_pincode,h_email,h_phone,h_pw,h_image) VALUES (?, ?,?,?,?,?,?,?,?)");
if($stmt){
$stmt->bind_param("sssssssss",$name,$build,$district,$state,$pincode,$email,$phone,$pass,$img);
define ('SITE_ROOT','C:\xampp\htdocs\WEB');

// set parameters and execute
$name=$_POST['name'];
//$dob=$_POST['dob'];
//$gender=$_POST['gender'];
$build=$_POST['houseno'];
$district=$_POST['district'];
$state=$_POST['state'];
$pincode=$_POST['pincode'];
$email=$_POST['email'];
$phone=$_POST['phonenumber'];
$pass=password_hash($_POST['password'],PASSWORD_DEFAULT);
$img=$_FILES['photo']['name'];

if ($_FILES['photo']['name']!="") {
  	// Get image name
  	$img = $_FILES['photo']['name'];
  	// Get text
  //	$image_text = mysqli_real_escape_string($db, $_POST['image_text']);

  	// image file directory
  	$target = "\images/".$img;

  //	$sql = "INSERT INTO image (image, image_text) VALUES ('$image', '$image_text')";
  	// execute query
  	//mysqli_query($db, $sql);

  	if (move_uploaded_file($_FILES['photo']['tmp_name'], SITE_ROOT.$target)) {
  		echo "Image uploaded successfully";
  	}else{
  		echo "Failed to upload image";
  	}
	}
	else {
	 $img="empty";
	}
//	$img="empty";
//$photo=$_POST['photo'];

if($stmt->execute())
{
	//echo "inserted";
  //echo "ok";

            //  header("location:http://localhost/WEB/hospital-login.html");
  //}
  echo "<script> window.alert('$name - Autogenerated User Id is:.$stmt->insert_id. Please Use this to login');
  window.location.replace('../hospital-login.html');

</script>";


}
else
{
	echo $stmt->error;
}
$stmt->close();

//echo "inseted";
}


$conn->close();
?>
